name: Go CI

on:
  push:
    branches-ignore:
      - renovate/**
    paths:
      - '.github/workflows/**.yml'
      - 'src/**'
      - 'go.*'
      - '*.go'
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+' # Push events to matching v*, i.e. v20.15.10
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/**.yml'
      - 'src/**'
      - 'go.*'
      - '*.go'

jobs:

  strongo_workflow:
    permissions:
      contents: write
    uses: strongo/go-ci-action/.github/workflows/workflow.yml@main
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
